# Generated by Django 4.2.20 on 2026-07-10 05:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_code', models.CharField(max_length=20, unique=True, verbose_name='银行代码')),
                ('bank_name', models.CharField(max_length=100, verbose_name='银行名称')),
                ('channel_type', models.CharField(choices=[('online', '网银支付'), ('wire', '电汇'), ('ach', 'ACH转账'), ('realtime', '实时支付')], default='online', max_length=20, verbose_name='通道类型')),
                ('status', models.CharField(choices=[('active', '正常'), ('suspended', '暂停'), ('maintenance', '维护中'), ('offline', '下线')], default='active', max_length=20, verbose_name='状态')),
                ('priority', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='优先级')),
                ('success_rate', models.DecimalField(decimal_places=2, default=99.0, max_digits=5, verbose_name='成功率')),
                ('avg_response_time', models.IntegerField(default=500, verbose_name='平均响应时间(ms)')),
                ('daily_limit', models.DecimalField(decimal_places=2, default=999999999.99, max_digits=18, verbose_name='日限额')),
                ('fee_rate', models.DecimalField(decimal_places=4, default=0.001, max_digits=5, verbose_name='手续费率')),
                ('min_fee', models.DecimalField(decimal_places=2, default=1.0, max_digits=12, verbose_name='最低手续费')),
                ('max_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=12, verbose_name='最高手续费')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='API端点')),
                ('health_check_url', models.URLField(blank=True, verbose_name='健康检查URL')),
                ('supported_currencies', models.JSONField(default=list, verbose_name='支持币种')),
                ('supported_countries', models.JSONField(default=list, verbose_name='支持国家')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '银行通道',
                'verbose_name_plural': '银行通道',
                'db_table': 'routing_bank_channel',
                'ordering': ['priority', 'bank_code'],
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('amount', '按金额'), ('currency', '按币种'), ('country', '按国家'), ('priority', '按优先级'), ('cost', '按成本'), ('success_rate', '按成功率'), ('balanced', '负载均衡')], default='priority', max_length=20, verbose_name='规则类型')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('priority', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='优先级')),
                ('conditions', models.JSONField(default=dict, verbose_name='条件配置')),
                ('weight', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='权重')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('fallback_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_rules', to='routing.bankchannel', verbose_name='兜底通道')),
                ('target_channels', models.ManyToManyField(blank=True, to='routing.bankchannel', verbose_name='目标通道')),
            ],
            options={
                'verbose_name': '路由规则',
                'verbose_name_plural': '路由规则',
                'db_table': 'routing_rule',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoutingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(blank=True, max_length=64, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='金额')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('retry', '重试'), ('timeout', '超时')], default='success', max_length=20, verbose_name='结果')),
                ('response_time', models.IntegerField(default=0, verbose_name='响应时间(ms)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('request_data', models.JSONField(default=dict, verbose_name='请求数据')),
                ('response_data', models.JSONField(default=dict, verbose_name='响应数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routing.bankchannel', verbose_name='选择通道')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routing.routingrule', verbose_name='匹配规则')),
            ],
            options={
                'verbose_name': '路由日志',
                'verbose_name_plural': '路由日志',
                'db_table': 'routing_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
