# Generated by Django 4.2.20 on 2026-07-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_bank_channel_balances_and_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankchannel',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='国家'),
        ),
    ]
