# Generated by Django 4.2.20 on 2026-07-10 04:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('agent_no', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='代理编号')),
                ('agent_name', models.CharField(max_length=128, verbose_name='代理名称')),
                ('short_name', models.CharField(blank=True, max_length=64, verbose_name='简称')),
                ('level', models.CharField(choices=[('LEVEL_1', '一级代理'), ('LEVEL_2', '二级代理'), ('LEVEL_3', '三级代理')], default='LEVEL_1', max_length=16, verbose_name='代理等级')),
                ('status', models.CharField(choices=[('ACTIVE', '活跃'), ('SUSPENDED', '暂停'), ('CLOSED', '关闭')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('contact_name', models.CharField(blank=True, max_length=64, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('commission_rate', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='佣金比例')),
                ('max_merchant_count', models.IntegerField(default=0, verbose_name='最大商户数')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '代理商',
                'verbose_name_plural': '代理商',
                'db_table': 'agent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('commission_no', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='佣金单号')),
                ('order_count', models.IntegerField(default=0, verbose_name='订单笔数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='交易总额')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='佣金金额')),
                ('status', models.CharField(choices=[('PENDING', '待结算'), ('SETTLED', '已结算'), ('PAID', '已支付')], default='PENDING', max_length=16, verbose_name='状态')),
                ('settle_date', models.DateField(blank=True, null=True, verbose_name='结算日期')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='agent.agent', verbose_name='代理商')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_commissions', to='merchant.merchant', verbose_name='商户')),
            ],
            options={
                'verbose_name': '代理佣金',
                'verbose_name_plural': '代理佣金',
                'db_table': 'agent_commission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMerchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('commission_rate', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='分佣比例')),
                ('effective_from', models.DateField(verbose_name='生效日期')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_relations', to='agent.agent', verbose_name='代理商')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_relations', to='merchant.merchant', verbose_name='商户')),
            ],
            options={
                'verbose_name': '代理商户关联',
                'verbose_name_plural': '代理商户关联',
                'db_table': 'agent_merchant',
                'ordering': ['-created_at'],
                'unique_together': {('agent', 'merchant')},
            },
        ),
    ]
