# Generated by Django 4.2.20 on 2026-07-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='business_license_file',
            field=models.CharField(blank=True, max_length=512, verbose_name='营业执照文件'),
        ),
        migrations.AddField(
            model_name='agent',
            name='business_license_no',
            field=models.CharField(blank=True, max_length=64, verbose_name='营业执照号'),
        ),
        migrations.AddField(
            model_name='agent',
            name='business_scope',
            field=models.CharField(blank=True, max_length=512, verbose_name='经营范围'),
        ),
        migrations.AddField(
            model_name='agent',
            name='established_date',
            field=models.DateField(blank=True, null=True, verbose_name='成立日期'),
        ),
        migrations.AddField(
            model_name='agent',
            name='id_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='证件类型'),
        ),
        migrations.AddField(
            model_name='agent',
            name='kyc_documents',
            field=models.JSONField(blank=True, default=dict, verbose_name='资质材料'),
        ),
        migrations.AddField(
            model_name='agent',
            name='kyc_status',
            field=models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='PENDING', max_length=16, verbose_name='KYC状态'),
        ),
        migrations.AddField(
            model_name='agent',
            name='legal_person',
            field=models.CharField(blank=True, max_length=64, verbose_name='法人姓名'),
        ),
        migrations.AddField(
            model_name='agent',
            name='legal_person_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='法人证件号'),
        ),
        migrations.AddField(
            model_name='agent',
            name='registered_address',
            field=models.CharField(blank=True, max_length=256, verbose_name='注册地址'),
        ),
        migrations.AddField(
            model_name='agent',
            name='registered_capital',
            field=models.CharField(blank=True, max_length=64, verbose_name='注册资本'),
        ),
        migrations.AddField(
            model_name='agent',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='审核备注'),
        ),
        migrations.AddField(
            model_name='agent',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='agent',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=64, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='agent',
            name='settlement_account_holder',
            field=models.CharField(blank=True, max_length=128, verbose_name='账户持有人'),
        ),
        migrations.AddField(
            model_name='agent',
            name='settlement_account_no',
            field=models.CharField(blank=True, max_length=64, verbose_name='对公账户'),
        ),
        migrations.AddField(
            model_name='agent',
            name='settlement_bank_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='结算银行'),
        ),
        migrations.AddField(
            model_name='agent',
            name='swift_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='SWIFT代码'),
        ),
    ]
