# Generated by Django 4.2.20 on 2026-07-17 06:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_business_license_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentFeeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('fee_type', models.CharField(choices=[('TRANSACTION', '交易手续费'), ('SETTLEMENT', '结算手续费'), ('SERVICE', '服务费')], default='TRANSACTION', max_length=16, verbose_name='费用类型')),
                ('currency', models.CharField(choices=[('USD', '美元'), ('EUR', '欧元'), ('GBP', '英镑'), ('CNY', '人民币'), ('JPY', '日元'), ('HKD', '港币')], default='USD', max_length=4, verbose_name='币种')),
                ('rate', models.DecimalField(decimal_places=6, default=0, help_text='百分比费率，如 0.5 表示 0.5%', max_digits=8, verbose_name='费率(%)')),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, help_text='每笔固定收取金额', max_digits=14, verbose_name='固定手续费')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='最低收费')),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, help_text='0 表示不设上限', max_digits=14, verbose_name='最高收费')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_configs', to='agent.agent', verbose_name='代理商')),
            ],
            options={
                'verbose_name': '代理商费率配置',
                'verbose_name_plural': '代理商费率配置',
                'db_table': 'agent_fee_config',
                'ordering': ['agent', 'fee_type', 'currency'],
                'unique_together': {('agent', 'fee_type', 'currency')},
            },
        ),
    ]
