# Generated by Django 4.2.30 on 2026-07-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentfeeconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='kyc_documents',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='kyc_status',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='review_comment',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='reviewed_by',
        ),
    ]
