# Generated by Django 4.2.20 on 2026-08-20 03:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_remove_kyc_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentKYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('tier', models.CharField(choices=[('TIER_1', '一级(基础)'), ('TIER_2', '二级(标准)'), ('TIER_3', '三级(增强)')], default='TIER_1', max_length=8, verbose_name='KYC等级')),
                ('legal_person', models.CharField(max_length=64, verbose_name='法人姓名')),
                ('id_type', models.CharField(choices=[('ID_CARD', '身份证'), ('PASSPORT', '护照'), ('BUSINESS_LICENSE', '营业执照')], default='BUSINESS_LICENSE', max_length=16, verbose_name='证件类型')),
                ('id_number', models.CharField(max_length=256, verbose_name='证件号(加密)')),
                ('id_number_plain', models.CharField(blank=True, max_length=64, verbose_name='证件号')),
                ('business_license', models.CharField(max_length=256, verbose_name='营业执照号(加密)')),
                ('business_scope', models.TextField(blank=True, verbose_name='经营范围')),
                ('registered_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='注册资本')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='成立日期')),
                ('registered_address', models.CharField(blank=True, max_length=256, verbose_name='注册地址')),
                ('kyc_status', models.CharField(choices=[('PENDING', '待提交'), ('SUBMITTED', '已提交'), ('UNDER_REVIEW', '审核中'), ('APPROVED', '通过'), ('REJECTED', '驳回')], default='PENDING', max_length=16, verbose_name='KYC状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('reviewed_by', models.CharField(blank=True, max_length=64, verbose_name='审核人')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comment', models.CharField(blank=True, max_length=256, verbose_name='审核意见')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='agent.agent', verbose_name='代理商')),
            ],
            options={
                'verbose_name': '代理KYC',
                'verbose_name_plural': '代理KYC',
                'db_table': 'agent_kyc',
            },
        ),
    ]
