# Generated by Django 4.2.20 on 2026-08-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_agentkyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='agent',
            name='api_secret',
            field=models.CharField(blank=True, max_length=256, verbose_name='API 密钥'),
        ),
    ]
