# Generated by Django 4.2.20 on 2026-07-06 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOrderSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('report_date', models.DateField(db_index=True, unique=True, verbose_name='报表日期')),
                ('total_merchants', models.IntegerField(default=0, verbose_name='活跃商户数')),
                ('total_orders', models.IntegerField(default=0, verbose_name='总订单笔数')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='总金额')),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='总手续费')),
                ('total_refunds', models.IntegerField(default=0, verbose_name='总退款笔数')),
                ('total_refund_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='总退款金额')),
                ('settled_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='已清算金额')),
            ],
            options={
                'verbose_name': '平台订单汇总表',
                'verbose_name_plural': '平台订单汇总表',
                'db_table': 'platform_order_summary',
            },
        ),
        migrations.CreateModel(
            name='ChannelFeeReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('report_date', models.DateField(db_index=True, verbose_name='报表日期')),
                ('bank_code', models.CharField(max_length=16, verbose_name='银行编码')),
                ('bank_name', models.CharField(max_length=128, verbose_name='银行名称')),
                ('total_orders', models.IntegerField(default=0, verbose_name='订单笔数')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='交易总金额')),
                ('channel_fee', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='渠道手续费')),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='平台手续费')),
            ],
            options={
                'verbose_name': '渠道手续费结算表',
                'verbose_name_plural': '渠道手续费结算表',
                'db_table': 'channel_fee_report',
                'unique_together': {('report_date', 'bank_code')},
            },
        ),
        migrations.CreateModel(
            name='MerchantDailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('report_date', models.DateField(db_index=True, verbose_name='报表日期')),
                ('total_orders', models.IntegerField(default=0, verbose_name='订单笔数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='订单总金额')),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='手续费总额')),
                ('total_refunds', models.IntegerField(default=0, verbose_name='退款笔数')),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='退款总金额')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='净收单金额')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchant.merchant', verbose_name='商户')),
            ],
            options={
                'verbose_name': '商户日收单报表',
                'verbose_name_plural': '商户日收单报表',
                'db_table': 'merchant_daily_report',
                'unique_together': {('report_date', 'merchant')},
            },
        ),
    ]
