# Generated by Django 4.2.20 on 2026-08-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_lifecycle_controls'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channelfeereport',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='merchantdailyreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='channelfeereport',
            name='currency',
            field=models.CharField(blank=True, db_index=True, default='', max_length=3, verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='channelfeereport',
            name='data_watermark',
            field=models.DateTimeField(blank=True, null=True, verbose_name='数据水位'),
        ),
        migrations.AddField(
            model_name='merchantdailyreport',
            name='currency',
            field=models.CharField(blank=True, db_index=True, default='', max_length=3, verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='merchantdailyreport',
            name='data_watermark',
            field=models.DateTimeField(blank=True, null=True, verbose_name='数据水位'),
        ),
        migrations.AddField(
            model_name='platformordersummary',
            name='currency',
            field=models.CharField(blank=True, db_index=True, default='', max_length=3, verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='platformordersummary',
            name='data_watermark',
            field=models.DateTimeField(blank=True, null=True, verbose_name='数据水位'),
        ),
        migrations.AlterField(
            model_name='platformordersummary',
            name='report_date',
            field=models.DateField(db_index=True, verbose_name='报表日期'),
        ),
        migrations.AlterUniqueTogether(
            name='channelfeereport',
            unique_together={('report_date', 'bank_code', 'currency')},
        ),
        migrations.AlterUniqueTogether(
            name='merchantdailyreport',
            unique_together={('report_date', 'merchant', 'currency')},
        ),
        migrations.AlterUniqueTogether(
            name='platformordersummary',
            unique_together={('report_date', 'currency')},
        ),
    ]
