# Generated by Django 4.2.20 on 2026-07-06 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('merchant_no', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='商户编号')),
                ('merchant_name', models.CharField(max_length=128, verbose_name='商户名称')),
                ('short_name', models.CharField(blank=True, max_length=64, verbose_name='商户简称')),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('SUSPENDED', '暂停'), ('CLOSED', '已关闭')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('contact_name', models.CharField(blank=True, max_length=64, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('api_key', models.CharField(blank=True, max_length=64, unique=True, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=256, verbose_name='API 密钥(加密)')),
            ],
            options={
                'verbose_name': '商户',
                'verbose_name_plural': '商户',
                'db_table': 'merchant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantSettlementAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('bank_name', models.CharField(max_length=128, verbose_name='银行名称')),
                ('bank_branch', models.CharField(blank=True, max_length=128, verbose_name='支行')),
                ('account_name', models.CharField(max_length=128, verbose_name='账户名')),
                ('account_number', models.CharField(max_length=256, verbose_name='账号(加密)')),
                ('account_type', models.CharField(default='CORPORATE', max_length=16, verbose_name='账户类型')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认账户')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_accounts', to='merchant.merchant', verbose_name='商户')),
            ],
            options={
                'verbose_name': '商户结算账户',
                'verbose_name_plural': '商户结算账户',
                'db_table': 'merchant_settlement_account',
            },
        ),
        migrations.CreateModel(
            name='MerchantKYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('legal_person', models.CharField(max_length=64, verbose_name='法人姓名')),
                ('id_number', models.CharField(max_length=256, verbose_name='身份证号(加密)')),
                ('business_license', models.CharField(max_length=256, verbose_name='营业执照号(加密)')),
                ('business_scope', models.TextField(blank=True, verbose_name='经营范围')),
                ('registered_capital', models.DecimalField(decimal_places=2, max_digits=18, null=True, verbose_name='注册资本')),
                ('established_date', models.DateField(null=True, verbose_name='成立日期')),
                ('registered_address', models.CharField(blank=True, max_length=256, verbose_name='注册地址')),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='merchant.merchant', verbose_name='商户')),
            ],
            options={
                'verbose_name': '商户KYC',
                'verbose_name_plural': '商户KYC',
                'db_table': 'merchant_kyc',
            },
        ),
        migrations.CreateModel(
            name='MerchantFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('product_type', models.CharField(choices=[('ONLINE_BANK', '银行网银支付'), ('AUTHORIZED', '授权支付'), ('WIRE_TRANSFER', '转款汇款')], max_length=32, verbose_name='支付产品')),
                ('fee_model', models.CharField(choices=[('FIXED', '固定金额'), ('PERCENTAGE', '按比例'), ('TIERED', '阶梯费率')], max_length=16, verbose_name='费率模型')),
                ('fixed_fee', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='固定手续费')),
                ('fee_rate', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='手续费比例')),
                ('min_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='最低手续费')),
                ('max_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='最高手续费')),
                ('effective_from', models.DateField(verbose_name='生效日期')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='merchant.merchant', verbose_name='商户')),
            ],
            options={
                'verbose_name': '商户手续费',
                'verbose_name_plural': '商户手续费',
                'db_table': 'merchant_fee',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='MerchantPaymentProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('product_type', models.CharField(max_length=32, verbose_name='产品类型')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('max_single_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True, verbose_name='单笔限额')),
                ('daily_limit', models.DecimalField(decimal_places=2, max_digits=18, null=True, verbose_name='日限额')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_products', to='merchant.merchant', verbose_name='商户')),
            ],
            options={
                'verbose_name': '商户支付产品',
                'verbose_name_plural': '商户支付产品',
                'db_table': 'merchant_payment_product',
                'unique_together': {('merchant', 'product_type')},
            },
        ),
    ]
