# Generated by Django 4.2.20 on 2026-07-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='daily_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='日限额'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='days_to_expiry',
            field=models.IntegerField(blank=True, null=True, verbose_name='距到期天数'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='fee_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='手续费率'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='fixed_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='固定手续费'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='legal_person_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='法人姓名'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='证照到期日'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='max_single_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='单笔限额'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='next_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='下次审核日'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='risk_level',
            field=models.CharField(default='MEDIUM', max_length=16, verbose_name='风险等级'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='sanction_status',
            field=models.CharField(default='UN', max_length=16, verbose_name='制裁名单'),
        ),
        migrations.AddField(
            model_name='merchantkyc',
            name='id_number_plain',
            field=models.CharField(blank=True, max_length=64, verbose_name='证件号码'),
        ),
        migrations.AddField(
            model_name='merchantkyc',
            name='id_type',
            field=models.CharField(default='ID_CARD', max_length=16, verbose_name='证件类型'),
        ),
        migrations.AddField(
            model_name='merchantkyc',
            name='kyc_status',
            field=models.CharField(default='PENDING', max_length=16, verbose_name='KYC状态'),
        ),
        migrations.AddField(
            model_name='merchantkyc',
            name='nationality',
            field=models.CharField(blank=True, max_length=64, verbose_name='国籍'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '正常'), ('SUSPENDED', '暂停'), ('CLOSED', '已关闭'), ('PENDING', '待处理')], default='ACTIVE', max_length=16, verbose_name='状态'),
        ),
    ]
