# Generated by Django 4.2.20 on 2026-07-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_merchant_daily_limit_merchant_days_to_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantkyc',
            name='remark',
            field=models.TextField(blank=True, verbose_name='审核备注'),
        ),
        migrations.AddField(
            model_name='merchantkyc',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
    ]
