# Generated by Django 4.2.30 on 2026-07-20 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentfeeconfig'),
        ('merchant', '0003_merchantkyc_remark_merchantkyc_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_merchants', to='agent.agent', verbose_name='所属代理商'),
        ),
    ]
