# Generated by Django 4.2.20 on 2026-08-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_merchant_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='daily_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='每日笔数'),
        ),
    ]
