# Generated by Django 4.2.20 on 2026-08-27 00:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_merchant_daily_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantSplitConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('auto_split', models.BooleanField(default=True, verbose_name='自动分账')),
                ('settlement_cycle', models.IntegerField(default=1, verbose_name='结算周期T+N')),
                ('merchant_ratio', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=7, verbose_name='商户分账比例')),
                ('platform_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='平台分账比例')),
                ('agent_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='代理分账比例')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='split_config', to='merchant.merchant', verbose_name='商户')),
            ],
            options={
                'verbose_name': '商户分账属性',
                'verbose_name_plural': '商户分账属性',
                'db_table': 'merchant_split_config',
            },
        ),
    ]
