# Generated by Django 4.2.20 on 2026-07-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=64, verbose_name='操作人')),
                ('action', models.CharField(max_length=64, verbose_name='操作类型')),
                ('resource_type', models.CharField(max_length=64, verbose_name='资源类型')),
                ('resource_id', models.CharField(max_length=64, verbose_name='资源ID')),
                ('before_snapshot', models.JSONField(blank=True, null=True, verbose_name='变更前')),
                ('after_snapshot', models.JSONField(blank=True, null=True, verbose_name='变更后')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='audit_log_resourc_2570dd_idx'), models.Index(fields=['operator', 'created_at'], name='audit_log_operato_3078ab_idx')],
            },
        ),
    ]
