# Generated by Django 4.2.20 on 2026-07-10 04:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionScanRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('scan_no', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='扫描编号')),
                ('scan_type', models.CharField(choices=[('TRANSACTION', '交易扫描'), ('MERCHANT_ONBOARDING', '商户入驻'), ('AGENT_ONBOARDING', '代理入驻'), ('BATCH', '批量扫描')], max_length=32, verbose_name='扫描类型')),
                ('target_type', models.CharField(max_length=32, verbose_name='目标类型')),
                ('target_id', models.CharField(max_length=64, verbose_name='目标ID')),
                ('target_name', models.CharField(max_length=256, verbose_name='目标名称')),
                ('status', models.CharField(choices=[('PENDING', '待扫描'), ('SCANNING', '扫描中'), ('CLEAR', '通过'), ('HIT', '命中'), ('MANUAL_REVIEW', '人工复核')], default='PENDING', max_length=16, verbose_name='状态')),
                ('hit_count', models.IntegerField(default=0, verbose_name='命中数')),
                ('operator', models.CharField(blank=True, max_length=64, verbose_name='操作人')),
                ('scan_result', models.JSONField(default=dict, verbose_name='扫描结果')),
            ],
            options={
                'verbose_name': '制裁扫描记录',
                'verbose_name_plural': '制裁扫描记录',
                'db_table': 'sanction_scan_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SanctionList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('entity_name', models.CharField(db_index=True, max_length=256, verbose_name='实体名称')),
                ('alias_names', models.TextField(blank=True, verbose_name='别名(逗号分隔)')),
                ('entity_type', models.CharField(choices=[('PERSON', '个人'), ('COMPANY', '企业'), ('VESSEL', '船只'), ('OTHER', '其他')], default='PERSON', max_length=32, verbose_name='实体类型')),
                ('list_type', models.CharField(choices=[('OFAC', 'OFAC(美国)'), ('UN', '联合国'), ('EU', '欧盟'), ('MPS', '公安部'), ('PBOC', '人民银行'), ('INTERNAL', '内部黑名单')], max_length=16, verbose_name='名单来源')),
                ('risk_level', models.CharField(choices=[('HIGH', '高风险'), ('MEDIUM', '中风险'), ('LOW', '低风险')], default='MEDIUM', max_length=8, verbose_name='风险等级')),
                ('id_number', models.CharField(blank=True, max_length=256, verbose_name='证件号码')),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='国家/地区')),
                ('sanction_reason', models.TextField(blank=True, verbose_name='制裁原因')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '制裁名单',
                'verbose_name_plural': '制裁名单',
                'db_table': 'sanction_list',
                'ordering': ['-risk_level', 'entity_name'],
                'indexes': [models.Index(fields=['entity_name', 'list_type'], name='sanction_li_entity__39e4ef_idx'), models.Index(fields=['risk_level', 'is_active'], name='sanction_li_risk_le_371d52_idx')],
            },
        ),
        migrations.CreateModel(
            name='SanctionHitDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('match_field', models.CharField(max_length=64, verbose_name='匹配字段')),
                ('match_value', models.CharField(max_length=512, verbose_name='匹配值')),
                ('match_score', models.FloatField(default=0, verbose_name='匹配分数')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='已处理')),
                ('resolution', models.CharField(choices=[('TRUE_HIT', '确认命中'), ('FALSE_POSITIVE', '误报'), ('PENDING', '待处理')], default='PENDING', max_length=16, verbose_name='处理结果')),
                ('resolved_by', models.CharField(blank=True, max_length=64, verbose_name='处理人')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('sanction_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hits', to='compliance.sanctionlist', verbose_name='命中名单')),
                ('scan_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='compliance.sanctionscanrecord', verbose_name='扫描记录')),
            ],
            options={
                'verbose_name': '制裁命中明细',
                'verbose_name_plural': '制裁命中明细',
                'db_table': 'sanction_hit_detail',
                'ordering': ['-match_score'],
            },
        ),
    ]
