# Generated by Django 4.2.20 on 2026-07-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionlist',
            name='address',
            field=models.TextField(blank=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='sanctionlist',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=64, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='sanctionlist',
            name='nationality',
            field=models.CharField(blank=True, max_length=64, verbose_name='国籍'),
        ),
        migrations.AddField(
            model_name='sanctionlist',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=256, verbose_name='出生地点'),
        ),
        migrations.AddField(
            model_name='sanctionlist',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, help_text='制裁名单中的唯一编号，如 QDi.371, KPe.030', max_length=32, verbose_name='名单编号'),
        ),
        migrations.AlterField(
            model_name='sanctionlist',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='生效日期(列入名单日期)'),
        ),
    ]
