# Generated by Django 4.2.30 on 2026-07-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_sanctionlist_address_sanctionlist_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionlist',
            name='review_date',
            field=models.DateField(blank=True, help_text='根据风险等级自动计算: HIGH=30天 / MEDIUM=90天 / LOW=180天', null=True, verbose_name='复审日期'),
        ),
    ]
