# Generated by Django 4.2.20 on 2026-08-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_sanctionlist_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionlist',
            name='entity_type',
            field=models.CharField(choices=[('PERSON', '个人'), ('COMPANY', '企业'), ('CITY', '城市'), ('COUNTRY', '国家'), ('VESSEL', '船只'), ('OTHER', '其他')], default='PERSON', max_length=32, verbose_name='实体类型'),
        ),
    ]
