# Generated by Django 4.2.20 on 2026-07-10 05:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoopBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_code', models.CharField(max_length=20, unique=True, verbose_name='银行代码')),
                ('bank_name', models.CharField(max_length=100, verbose_name='银行名称')),
                ('bank_name_en', models.CharField(blank=True, max_length=100, verbose_name='银行英文名称')),
                ('swift_code', models.CharField(blank=True, max_length=20, verbose_name='SWIFT代码')),
                ('country', models.CharField(default='中国', max_length=50, verbose_name='国家/地区')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('status', models.CharField(choices=[('active', '正常合作'), ('suspended', '暂停合作'), ('terminated', '终止合作')], default='active', max_length=20, verbose_name='合作状态')),
                ('settlement_cycle', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='结算周期(天)')),
                ('daily_limit', models.DecimalField(decimal_places=2, default=999999999.99, max_digits=18, verbose_name='日限额')),
                ('support_wire', models.BooleanField(default=True, verbose_name='支持电汇')),
                ('support_ach', models.BooleanField(default=False, verbose_name='支持ACH')),
                ('support_realtime', models.BooleanField(default=False, verbose_name='支持实时支付')),
                ('nostro_account', models.CharField(blank=True, max_length=50, verbose_name='Nostro账户号')),
                ('nostro_currency', models.CharField(default='CNY', max_length=10, verbose_name='Nostro币种')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '合作银行',
                'verbose_name_plural': '合作银行',
                'db_table': 'param_coop_bank',
                'ordering': ['bank_code'],
            },
        ),
        migrations.CreateModel(
            name='FeeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_code', models.CharField(max_length=30, unique=True, verbose_name='模型代码')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('fee_type', models.CharField(choices=[('fixed', '固定费率'), ('tiered', '阶梯费率'), ('mixed', '混合费率')], default='fixed', max_length=20, verbose_name='费率类型')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('base_rate', models.DecimalField(decimal_places=6, default=0.003, max_digits=7, verbose_name='基础费率')),
                ('min_fee', models.DecimalField(decimal_places=2, default=1.0, max_digits=12, verbose_name='最低手续费')),
                ('max_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=12, verbose_name='最高手续费')),
                ('tier_config', models.JSONField(blank=True, default=dict, verbose_name='阶梯配置')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '手续费模型',
                'verbose_name_plural': '手续费模型',
                'db_table': 'param_fee_model',
                'ordering': ['model_code'],
            },
        ),
        migrations.CreateModel(
            name='BankFeeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('online', '网银支付'), ('wire', '电汇'), ('ach', 'ACH转账'), ('realtime', '实时支付')], default='online', max_length=20, verbose_name='通道类型')),
                ('override_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='覆盖费率')),
                ('override_min_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='覆盖最低手续费')),
                ('override_max_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='覆盖最高手续费')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='param.coopbank', verbose_name='合作银行')),
                ('fee_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='param.feemodel', verbose_name='手续费模型')),
            ],
            options={
                'verbose_name': '银行手续费配置',
                'verbose_name_plural': '银行手续费配置',
                'db_table': 'param_bank_fee_config',
                'ordering': ['bank', 'channel_type'],
                'unique_together': {('bank', 'fee_model', 'channel_type')},
            },
        ),
    ]
