# Generated by Django 4.2.20 on 2026-09-03 03:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0003_sync_risk_rating_daily_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceFeeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('singleton_key', models.CharField(default='default', max_length=16, unique=True, verbose_name='单例键')),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='固定手续费')),
                ('percent_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='例如 0.30 表示 0.30%', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='汇款百分比(%)')),
                ('max_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='最高手续费')),
                ('updated_by', models.CharField(blank=True, max_length=64, verbose_name='修改人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '汇款手续费配置',
                'verbose_name_plural': '汇款手续费配置',
                'db_table': 'param_remittance_fee_config',
            },
        ),
    ]
