# Generated by Django 4.2.20 on 2026-07-06 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NostroAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('account_no', models.CharField(max_length=32, unique=True, verbose_name='账户编号')),
                ('bank_code', models.CharField(max_length=16, verbose_name='银行编码')),
                ('bank_name', models.CharField(max_length=128, verbose_name='银行名称')),
                ('account_number', models.CharField(max_length=256, verbose_name='账号(加密)')),
                ('account_type', models.CharField(choices=[('SETTLEMENT', '结算账户'), ('COLLECTION', '收款账户'), ('RESERVE', '备付金账户')], default='COLLECTION', max_length=16, verbose_name='账户类型')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='币种')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='账面余额')),
                ('last_reconciled_balance', models.DecimalField(decimal_places=2, max_digits=18, null=True, verbose_name='最后对账余额')),
                ('last_reconciled_at', models.DateTimeField(null=True, verbose_name='最后对账时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'Nostro账户',
                'verbose_name_plural': 'Nostro账户',
                'db_table': 'nostro_account',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='用户ID')),
                ('bank_code', models.CharField(max_length=16, verbose_name='银行编码')),
                ('bank_name', models.CharField(max_length=128, verbose_name='银行名称')),
                ('account_holder', models.CharField(max_length=64, verbose_name='账户持有人')),
                ('account_number', models.CharField(max_length=256, verbose_name='账号(加密)')),
                ('bind_token', models.CharField(max_length=256, verbose_name='绑定Token(加密)')),
                ('status', models.CharField(choices=[('PENDING', '待验证'), ('ACTIVE', '已绑定'), ('EXPIRED', '已过期'), ('REVOKED', '已解绑')], default='PENDING', max_length=16, verbose_name='状态')),
                ('bind_at', models.DateTimeField(null=True, verbose_name='绑定时间')),
                ('expire_at', models.DateTimeField(null=True, verbose_name='授权过期时间')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchant.merchant', verbose_name='所属商户')),
            ],
            options={
                'verbose_name': '用户账户',
                'verbose_name_plural': '用户账户',
                'db_table': 'user_account',
                'unique_together': {('user_id', 'bank_code', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='UserPaymentDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='用户ID')),
                ('pay_method', models.CharField(max_length=32, verbose_name='支付方式')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='支付金额')),
                ('pay_time', models.DateTimeField(verbose_name='支付时间')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.useraccount', verbose_name='支付账户')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payment.paymentorder', verbose_name='支付订单')),
            ],
            options={
                'verbose_name': '用户支付明细',
                'verbose_name_plural': '用户支付明细',
                'db_table': 'user_payment_detail',
            },
        ),
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('transfer_no', models.CharField(max_length=32, unique=True, verbose_name='调拨单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='调拨金额')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='币种')),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('PROCESSING', '执行中'), ('SUCCESS', '已到账'), ('FAILED', '失败')], default='PENDING', max_length=16, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('executed_at', models.DateTimeField(null=True, verbose_name='执行时间')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='out_transfers', to='account.nostroaccount', verbose_name='调出账户')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_transfers', to='account.nostroaccount', verbose_name='调入账户')),
            ],
            options={
                'verbose_name': '资金调拨',
                'verbose_name_plural': '资金调拨',
                'db_table': 'fund_transfer',
                'ordering': ['-created_at'],
            },
        ),
    ]
