# Generated by Django 4.2.20 on 2026-07-13 06:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_merchantkyc_remark_merchantkyc_reviewed_at'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('deposit_no', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='入账单号')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='币种')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='入账金额')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝')], default='PENDING', max_length=16, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('reviewed_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='审核人')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comment', models.CharField(blank=True, max_length=256, verbose_name='审核意见')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='merchant.merchant', verbose_name='客户')),
            ],
            options={
                'verbose_name': '存款请求',
                'verbose_name_plural': '存款请求',
                'db_table': 'deposit_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'status'], name='deposit_req_merchan_167d76_idx'), models.Index(fields=['currency', 'status'], name='deposit_req_currenc_94a160_idx')],
            },
        ),
    ]
