# Generated by Django 4.2.20 on 2026-07-14 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_merchantkyc_remark_merchantkyc_reviewed_at'),
        ('account', '0002_depositrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='nostroaccount',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nostro_accounts', to='merchant.merchant', verbose_name='关联客户'),
        ),
    ]
