# Generated by Django 4.2.20 on 2026-07-14 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_nostroaccount_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='account.nostroaccount', verbose_name='入账账户'),
        ),
    ]
