# Generated by Django 4.2.30 on 2026-07-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_depositrequest_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='nostroaccount',
            name='close_reason',
            field=models.CharField(blank=True, max_length=256, verbose_name='注销原因'),
        ),
        migrations.AddField(
            model_name='nostroaccount',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='注销时间'),
        ),
        migrations.AddField(
            model_name='nostroaccount',
            name='daily_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='单日限额'),
        ),
        migrations.AddField(
            model_name='nostroaccount',
            name='max_single_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='单笔限额'),
        ),
    ]
