# Generated by Django 4.2.20 on 2026-08-11 02:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_refundfeeconfig_refundorder_refund_fee_amount_and_more'),
        ('merchant', '0005_merchant_daily_count'),
        ('account', '0005_nostroaccount_close_reason_nostroaccount_closed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('va_number', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='虚拟账号')),
                ('va_type', models.CharField(choices=[('VLA', 'Virtual Ledger Account'), ('VAV', 'Virtual Bank Account Number')], default='VAV', max_length=8, verbose_name='虚拟账户类型')),
                ('label', models.CharField(blank=True, max_length=128, verbose_name='虚拟账户名称')),
                ('reference', models.CharField(blank=True, max_length=64, verbose_name='业务参考号(订单号/商户号)')),
                ('bank_code', models.CharField(max_length=16, verbose_name='银行编码')),
                ('bank_name', models.CharField(max_length=128, verbose_name='银行名称')),
                ('account_holder', models.CharField(max_length=128, verbose_name='账户持有人')),
                ('routing_code', models.CharField(blank=True, max_length=32, verbose_name='本地路由码')),
                ('clearing_network', models.CharField(blank=True, max_length=16, verbose_name='本地清算网络(ACH/SEPA/FPS)')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='国家(ISO2)')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='币种')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('INACTIVE', '停用'), ('REVOKED', '已注销')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='开通时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='注销时间')),
                ('close_reason', models.CharField(blank=True, max_length=256, verbose_name='注销原因')),
                ('master_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virtual_accounts', to='account.nostroaccount', verbose_name='母账户(伞形实体账户)')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_accounts', to='merchant.merchant', verbose_name='关联客户')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_accounts', to='payment.paymentorder', verbose_name='关联订单(一笔一码)')),
            ],
            options={
                'verbose_name': '虚拟账户',
                'verbose_name_plural': '虚拟账户',
                'db_table': 'virtual_account',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'va_type', 'status'], name='virtual_acc_merchan_d8c797_idx'), models.Index(fields=['order'], name='virtual_acc_order_i_cd8fce_idx')],
            },
        ),
    ]
