# Generated by Django 4.2.20 on 2026-08-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_virtualaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualaccount',
            name='ledger_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='分类账余额'),
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='clearing_network',
            field=models.CharField(blank=True, choices=[('ACH', 'ACH (美国)'), ('SEPA', 'SEPA (欧元区)'), ('SEPA_INST', 'SEPA 即时'), ('FPS', 'FPS (香港)'), ('FAST', 'FAST (新加坡)'), ('CHAPS', 'CHAPS (英国)'), ('BACS', 'BACS (英国)'), ('SWIFT', 'SWIFT (跨境电汇)'), ('PIX', 'PIX (巴西)'), ('OTHER', '其他')], max_length=16, verbose_name='本地清算网络(ACH/SEPA/FPS)'),
        ),
    ]
