# Generated by Django 4.2.20 on 2026-08-20 03:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_agentkyc'),
        ('account', '0007_virtualaccount_ledger_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDisbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('disbursement_no', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='拨付单号')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='币种')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='拨付金额')),
                ('payee_bank_name', models.CharField(max_length=128, verbose_name='收款银行')),
                ('payee_account_no', models.CharField(max_length=64, verbose_name='收款账号')),
                ('payee_account_holder', models.CharField(blank=True, max_length=128, verbose_name='收款账户持有人')),
                ('swift_code', models.CharField(blank=True, max_length=16, verbose_name='SWIFT代码')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('status', models.CharField(choices=[('PENDING_FIRST_APPROVAL', '待一审'), ('PENDING_SECOND_APPROVAL', '待二审'), ('APPROVED', '已授权'), ('EXECUTING', '执行中'), ('SUCCESS', '拨付成功'), ('FAILED', '拨付失败'), ('REJECTED', '已驳回')], default='PENDING_FIRST_APPROVAL', max_length=24, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='授权完成时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('fail_reason', models.CharField(blank=True, max_length=256, verbose_name='失败原因')),
                ('notify_status', models.CharField(default='PENDING', max_length=16, verbose_name='通知状态')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='agent.agent', verbose_name='代理商')),
            ],
            options={
                'verbose_name': '代理资金拨付',
                'verbose_name_plural': '代理资金拨付',
                'db_table': 'agent_disbursement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='nostroaccount',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nostro账户', 'verbose_name_plural': 'Nostro账户'},
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='可用余额'),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='freeze_reason',
            field=models.CharField(blank=True, max_length=256, verbose_name='冻结原因'),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='冻结时间'),
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '启用'), ('INACTIVE', '停用'), ('FROZEN', '冻结'), ('REVOKED', '已注销')], default='ACTIVE', max_length=16, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='DisbursementApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('step', models.CharField(choices=[('FIRST', '一审'), ('SECOND', '二审')], max_length=8, verbose_name='审批环节')),
                ('approver', models.CharField(max_length=64, verbose_name='审批人')),
                ('action', models.CharField(choices=[('APPROVE', '通过'), ('REJECT', '驳回')], max_length=8, verbose_name='审批动作')),
                ('comment', models.CharField(blank=True, max_length=256, verbose_name='审批意见')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='审批时间')),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='account.agentdisbursement', verbose_name='拨付单')),
            ],
            options={
                'verbose_name': '拨付审批记录',
                'verbose_name_plural': '拨付审批记录',
                'db_table': 'disbursement_approval',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentDisbursementSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用自动拨付')),
                ('frequency', models.CharField(choices=[('DAILY', '每日'), ('WEEKLY', '每周'), ('MONTHLY', '每月')], default='MONTHLY', max_length=8, verbose_name='频度')),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='触发阈值(可结算账户余额)')),
                ('payee_bank_name', models.CharField(blank=True, max_length=128, verbose_name='收款银行')),
                ('payee_account_no', models.CharField(blank=True, max_length=64, verbose_name='收款账号')),
                ('payee_account_holder', models.CharField(blank=True, max_length=128, verbose_name='收款账户持有人')),
                ('swift_code', models.CharField(blank=True, max_length=16, verbose_name='SWIFT代码')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_schedule', to='agent.agent', verbose_name='代理商')),
            ],
            options={
                'verbose_name': '代理自动拨付计划',
                'verbose_name_plural': '代理自动拨付计划',
                'db_table': 'agent_disbursement_schedule',
            },
        ),
    ]
