# Generated by Django 4.2.20 on 2026-08-27 02:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_p0_core_gaps'),
        ('payment', '0006_prnconfig_alter_paymentorder_prn_code'),
        ('account', '0008_agentdisbursement_alter_nostroaccount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('entry_type', models.CharField(choices=[('CREDIT', '贷记'), ('DEBIT', '借记')], max_length=8, verbose_name='方向')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='金额')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='记账后余额')),
                ('source_type', models.CharField(db_index=True, default='PAYMENT', max_length=32, verbose_name='来源类型')),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='来源ID')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='摘要')),
            ],
            options={
                'verbose_name': 'VA分类账分录',
                'verbose_name_plural': 'VA分类账分录',
                'db_table': 'va_ledger_entry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='nostroaccount',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nostro_accounts', to='agent.agent', verbose_name='关联代理商'),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_accounts', to='agent.agent', verbose_name='关联代理商'),
        ),
        migrations.AlterField(
            model_name='nostroaccount',
            name='account_type',
            field=models.CharField(choices=[('SETTLEMENT', '结算账户'), ('COLLECTION', '收款账户'), ('RESERVE', '备付金账户'), ('CURRENT', '往来账户'), ('FEE', '手续费账户')], default='COLLECTION', max_length=16, verbose_name='账户类型'),
        ),
        migrations.AddIndex(
            model_name='virtualaccount',
            index=models.Index(fields=['agent', 'va_type', 'status'], name='virtual_acc_agent_i_07f0bf_idx'),
        ),
        migrations.AddField(
            model_name='valedgerentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='va_ledger_entries', to='payment.paymentorder', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='valedgerentry',
            name='virtual_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='account.virtualaccount', verbose_name='虚拟账户'),
        ),
        migrations.AddIndex(
            model_name='valedgerentry',
            index=models.Index(fields=['source_type', 'source_id', 'entry_type'], name='va_ledger_e_source__d6e2fd_idx'),
        ),
    ]
