# Generated by Django 4.2.20 on 2026-08-30 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0006_payment_analytics_money_movement'),
        ('payment', '0008_paymentorder_applied_fee_model_and_more'),
        ('account', '0009_p0_core_gaps'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_no', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='流水号')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='发生时间')),
                ('movement_type', models.CharField(choices=[('COLLECTION', '系统确认收款'), ('SETTLEMENT_PAYOUT', '清算出款'), ('REFUND', '退款'), ('FEE_SHARE', '手续费分润'), ('REVERSAL', '冲正')], max_length=24, verbose_name='类型')),
                ('status', models.CharField(choices=[('PENDING', '处理中'), ('SUCCESS', '成功'), ('FAILED', '失败')], default='SUCCESS', max_length=16, verbose_name='状态')),
                ('evidence_level', models.CharField(choices=[('UNVERIFIED', '尚未证实'), ('SYSTEM_CONFIRMED', '系统确认'), ('BANK_CONFIRMED', '银行凭证')], default='SYSTEM_CONFIRMED', max_length=24, verbose_name='证据等级')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='金额')),
                ('currency', models.CharField(max_length=3, verbose_name='币种')),
                ('from_party_type', models.CharField(blank=True, default='', max_length=32, verbose_name='付款方类型')),
                ('from_party_id', models.CharField(blank=True, default='', max_length=64, verbose_name='付款方ID')),
                ('from_account', models.CharField(blank=True, default='', max_length=128, verbose_name='付款账号')),
                ('to_party_type', models.CharField(blank=True, default='', max_length=32, verbose_name='收款方类型')),
                ('to_party_id', models.CharField(blank=True, default='', max_length=64, verbose_name='收款方ID')),
                ('to_account', models.CharField(blank=True, default='', max_length=128, verbose_name='收款账号')),
                ('bank_code', models.CharField(blank=True, default='', max_length=16, verbose_name='银行编码')),
                ('bank_txn_id', models.CharField(blank=True, default='', max_length=64, verbose_name='银行流水号')),
                ('source_type', models.CharField(db_index=True, max_length=32, verbose_name='来源类型')),
                ('source_id', models.CharField(db_index=True, max_length=64, verbose_name='来源ID')),
                ('remark', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='附加信息')),
                ('payment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_movements', to='payment.paymentorder', verbose_name='支付订单')),
                ('refund_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_movements', to='payment.refundorder', verbose_name='退款单')),
                ('settlement_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_movements', to='settlement.settlementbatch', verbose_name='清算批次')),
            ],
            options={
                'verbose_name': '资金流水',
                'verbose_name_plural': '资金流水',
                'db_table': 'money_movement',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['payment_order', 'movement_type'], name='money_movem_payment_1532bb_idx'), models.Index(fields=['currency', 'occurred_at'], name='money_movem_currenc_685394_idx'), models.Index(fields=['status', 'evidence_level'], name='money_movem_status_022a60_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='moneymovement',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id', 'movement_type'), name='uniq_money_movement_source'),
        ),
    ]
