# Generated by Django 4.2.20 on 2026-07-06 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NostroBalanceCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('check_date', models.DateField(verbose_name='核对日期')),
                ('platform_balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='平台账面余额')),
                ('bank_statement_balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='银行对账单余额')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='差额')),
                ('is_balanced', models.BooleanField(default=True, verbose_name='是否平衡')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'Nostro余额核对',
                'verbose_name_plural': 'Nostro余额核对',
                'db_table': 'nostro_balance_check',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('batch_no', models.CharField(max_length=32, unique=True, verbose_name='对账批次号')),
                ('bank_code', models.CharField(max_length=16, verbose_name='银行编码')),
                ('bank_name', models.CharField(blank=True, max_length=128, verbose_name='银行名称')),
                ('reconciliation_date', models.DateField(db_index=True, verbose_name='对账日')),
                ('statement_file', models.CharField(blank=True, max_length=512, verbose_name='银行对账单文件路径')),
                ('total_count_bank', models.IntegerField(default=0, verbose_name='银行端总笔数')),
                ('total_amount_bank', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='银行端总金额')),
                ('total_count_platform', models.IntegerField(default=0, verbose_name='平台端总笔数')),
                ('total_amount_platform', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='平台端总金额')),
                ('match_count', models.IntegerField(default=0, verbose_name='匹配成功笔数')),
                ('match_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='匹配成功金额')),
                ('diff_count', models.IntegerField(default=0, verbose_name='差异笔数')),
                ('diff_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='差异金额')),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('FETCHING', '获取文件中'), ('MATCHING', '匹配中'), ('MATCHED', '已匹配'), ('DIFF', '存在差异'), ('RESOLVED', '差异已处理')], default='PENDING', max_length=16, verbose_name='状态')),
                ('started_at', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '对账批次',
                'verbose_name_plural': '对账批次',
                'db_table': 'reconciliation_batch',
                'ordering': ['-reconciliation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationDiff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('diff_type', models.CharField(choices=[('BANK_ONLY', '银行有平台无'), ('PLATFORM_ONLY', '平台有银行无'), ('AMOUNT_DIFF', '金额不一致'), ('STATUS_DIFF', '状态不一致')], max_length=16, verbose_name='差异类型')),
                ('order_no', models.CharField(blank=True, max_length=32, null=True, verbose_name='平台订单号')),
                ('bank_txn_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='银行交易流水号')),
                ('txn_time', models.DateTimeField(blank=True, null=True, verbose_name='交易时间')),
                ('amount_bank', models.DecimalField(decimal_places=2, max_digits=18, null=True, verbose_name='银行端金额')),
                ('amount_platform', models.DecimalField(decimal_places=2, max_digits=18, null=True, verbose_name='平台端金额')),
                ('resolution', models.CharField(choices=[('PENDING', '待处理'), ('ADJUST_BANK', '以银行为准'), ('ADJUST_PLATFORM', '以平台为准'), ('MANUAL_CHECK', '人工核查'), ('IGNORED', '忽略')], default='PENDING', max_length=16, verbose_name='处理方式')),
                ('resolution_note', models.TextField(blank=True, verbose_name='处理备注')),
                ('resolved_by', models.CharField(blank=True, max_length=64, verbose_name='处理人')),
                ('resolved_at', models.DateTimeField(null=True, verbose_name='处理时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs', to='reconciliation.reconciliationbatch', verbose_name='对账批次')),
            ],
            options={
                'verbose_name': '对账差异',
                'verbose_name_plural': '对账差异',
                'db_table': 'reconciliation_diff',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reconciliationbatch',
            index=models.Index(fields=['bank_code', 'reconciliation_date'], name='reconciliat_bank_co_00bf86_idx'),
        ),
        migrations.AddField(
            model_name='nostrobalancecheck',
            name='nostro_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.nostroaccount', verbose_name='Nostro账户'),
        ),
    ]
