# Generated by Django 4.2.20 on 2026-07-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationdiff',
            name='prn_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='PRN码'),
        ),
    ]
