# Generated by Django 4.2.20 on 2026-08-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_reconciliationdiff_prn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationbatch',
            name='recon_type',
            field=models.CharField(db_index=True, default='TRANSACTION', max_length=24, verbose_name='对账类型'),
        ),
    ]
