# Generated by Django 4.2.20 on 2026-08-27 02:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0003_feature_gap_split_and_recon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconAlertConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('webhook_url', models.CharField(blank=True, max_length=512, verbose_name='Webhook URL')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='告警邮箱')),
            ],
            options={
                'verbose_name': '对账预警配置',
                'verbose_name_plural': '对账预警配置',
                'db_table': 'recon_alert_config',
            },
        ),
        migrations.CreateModel(
            name='ReconAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('severity', models.CharField(choices=[('WARNING', '警告'), ('CRITICAL', '严重')], default='WARNING', max_length=16, verbose_name='级别')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('channel', models.CharField(choices=[('IN_APP', '站内'), ('WEBHOOK', 'Webhook'), ('EMAIL', '邮件')], default='IN_APP', max_length=16, verbose_name='渠道')),
                ('status', models.CharField(choices=[('OPEN', '待确认'), ('ACKED', '已确认')], default='OPEN', max_length=16, verbose_name='状态')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='投递时间')),
                ('delivery_error', models.CharField(blank=True, max_length=256, verbose_name='投递失败原因')),
                ('acked_by', models.CharField(blank=True, max_length=64, verbose_name='确认人')),
                ('acked_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='reconciliation.reconciliationbatch', verbose_name='对账批次')),
            ],
            options={
                'verbose_name': '对账预警',
                'verbose_name_plural': '对账预警',
                'db_table': 'recon_alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
