# Generated by Django 4.2.20 on 2026-07-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronboarding',
            name='id_back_image',
            field=models.TextField(blank=True, verbose_name='法人证件背面'),
        ),
        migrations.AlterField(
            model_name='useronboarding',
            name='id_front_image',
            field=models.TextField(blank=True, verbose_name='法人证件正面'),
        ),
        migrations.AlterField(
            model_name='useronboarding',
            name='license_image',
            field=models.TextField(blank=True, verbose_name='营业执照图片'),
        ),
    ]
