# Generated by Django 4.2.20 on 2026-07-10 02:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='权限编码')),
                ('name', models.CharField(max_length=128, verbose_name='权限名称')),
                ('resource', models.CharField(choices=[('merchant', '商户管理'), ('payment', '支付管理'), ('refund', '退款管理'), ('account', '账户管理'), ('reconciliation', '对账管理'), ('settlement', '清算管理'), ('report', '报表查询'), ('system', '系统管理')], max_length=64, verbose_name='资源模块')),
                ('action', models.CharField(max_length=32, verbose_name='操作类型')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'system_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='角色编码')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统内置')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'system_role',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('password_hash', models.CharField(max_length=256, verbose_name='密码哈希')),
                ('real_name', models.CharField(max_length=64, verbose_name='真实姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_locked', models.BooleanField(default=False, verbose_name='锁定')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='锁定至')),
                ('login_failed_count', models.PositiveSmallIntegerField(default=0, verbose_name='登录失败次数')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
            ],
            options={
                'verbose_name': '运营后台用户',
                'verbose_name_plural': '运营后台用户',
                'db_table': 'system_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.systemuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'db_table': 'user_role',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.permission', verbose_name='权限')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色权限',
                'verbose_name_plural': '角色权限',
                'db_table': 'role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名快照')),
                ('action', models.CharField(choices=[('LOGIN', '登录'), ('LOGOUT', '登出'), ('CREATE', '创建'), ('UPDATE', '修改'), ('DELETE', '删除'), ('APPROVE', '审批'), ('EXPORT', '导出')], max_length=32, verbose_name='操作类型')),
                ('resource', models.CharField(max_length=64, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, max_length=128, verbose_name='资源ID')),
                ('detail', models.JSONField(default=dict, verbose_name='操作详情')),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败')], default='SUCCESS', max_length=16, verbose_name='状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rbac.systemuser', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='operation_l_user_id_c9af97_idx'), models.Index(fields=['action', 'resource', 'created_at'], name='operation_l_action_bbf0ce_idx')],
            },
        ),
    ]
