# Generated by Django 4.2.20 on 2026-07-06 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('batch_no', models.CharField(max_length=32, unique=True, verbose_name='清算批次号')),
                ('settle_date', models.DateField(db_index=True, verbose_name='清算日期')),
                ('total_count', models.IntegerField(default=0, verbose_name='订单总笔数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='订单总金额')),
                ('fee_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='手续费总额')),
                ('settle_net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='净结算金额')),
                ('status', models.CharField(choices=[('PENDING', '待清算'), ('PROCESSING', '清算中'), ('SETTLED', '已清算'), ('FAILED', '清算失败')], default='PENDING', max_length=16, verbose_name='状态')),
                ('settled_at', models.DateTimeField(null=True, verbose_name='清算完成时间')),
                ('fail_reason', models.CharField(blank=True, max_length=256, verbose_name='失败原因')),
                ('settlement_account_info', models.JSONField(default=dict, verbose_name='结算账户信息快照')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_batches', to='merchant.merchant', verbose_name='商户')),
            ],
            options={
                'verbose_name': '清算批次',
                'verbose_name_plural': '清算批次',
                'db_table': 'settlement_batch',
                'ordering': ['-settle_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('order_no', models.CharField(max_length=32, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='订单金额')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='手续费')),
                ('settle_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='结算金额')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='settlement.settlementbatch', verbose_name='清算批次')),
                ('payment_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payment.paymentorder', verbose_name='支付订单')),
            ],
            options={
                'verbose_name': '清算明细',
                'verbose_name_plural': '清算明细',
                'db_table': 'settlement_detail',
            },
        ),
        migrations.CreateModel(
            name='FeeShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('channel_fee', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='渠道手续费')),
                ('platform_fee', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='平台手续费')),
                ('agent_fee', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='代理商分润')),
                ('settlement_detail', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='settlement.settlementdetail', verbose_name='清算明细')),
            ],
            options={
                'verbose_name': '手续费分润',
                'verbose_name_plural': '手续费分润',
                'db_table': 'fee_share',
            },
        ),
        migrations.CreateModel(
            name='DifferenceWriteOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('write_off_no', models.CharField(max_length=32, unique=True, verbose_name='销账单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='销账金额')),
                ('reason', models.CharField(max_length=256, verbose_name='原因')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('APPROVED', '已审批'), ('WRITTEN_OFF', '已销账'), ('REJECTED', '已驳回')], default='PENDING', max_length=16, verbose_name='状态')),
                ('applied_by', models.CharField(max_length=64, verbose_name='申请人')),
                ('approved_by', models.CharField(blank=True, max_length=64, verbose_name='审批人')),
                ('approved_at', models.DateTimeField(null=True, verbose_name='审批时间')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchant.merchant', verbose_name='商户')),
            ],
            options={
                'verbose_name': '差异代销账',
                'verbose_name_plural': '差异代销账',
                'db_table': 'difference_write_off',
            },
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['merchant', 'settle_date'], name='settlement__merchan_da03dd_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['status', 'settle_date'], name='settlement__status_053c1d_idx'),
        ),
    ]
