# Generated by Django 4.2.30 on 2026-07-20 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentfeeconfig'),
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeshare',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_shares', to='agent.agent', verbose_name='代理商'),
        ),
        migrations.AddField(
            model_name='feeshare',
            name='agent_name',
            field=models.CharField(default='', max_length=128, verbose_name='代理商名称'),
        ),
        migrations.AddField(
            model_name='feeshare',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='订单金额'),
        ),
        migrations.AddField(
            model_name='feeshare',
            name='bank_channel_name',
            field=models.CharField(default='', max_length=128, verbose_name='银行渠道'),
        ),
        migrations.AddField(
            model_name='feeshare',
            name='merchant_name',
            field=models.CharField(default='', max_length=128, verbose_name='商户名称'),
        ),
        migrations.AddField(
            model_name='feeshare',
            name='order_no',
            field=models.CharField(default='', max_length=32, verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='feeshare',
            name='total_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='商户手续费总额'),
        ),
        migrations.AlterField(
            model_name='feeshare',
            name='agent_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='代理商佣金'),
        ),
        migrations.AlterField(
            model_name='feeshare',
            name='platform_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='平台净收益'),
        ),
        migrations.AddIndex(
            model_name='feeshare',
            index=models.Index(fields=['agent'], name='fee_share_agent_i_735c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='feeshare',
            index=models.Index(fields=['order_no'], name='fee_share_order_n_da2df5_idx'),
        ),
        migrations.AddIndex(
            model_name='feeshare',
            index=models.Index(fields=['merchant_name'], name='fee_share_merchan_9db35f_idx'),
        ),
    ]
