# Generated by Django 4.2.30 on 2026-07-20 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentorder_prn_code_alter_paymentorder_status'),
        ('settlement', '0002_feeshare_agent_feeshare_agent_name_feeshare_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeshare',
            name='payment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_shares', to='payment.paymentorder', verbose_name='汇款订单'),
        ),
        migrations.AlterField(
            model_name='feeshare',
            name='settlement_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settlement.settlementdetail', verbose_name='清算明细'),
        ),
    ]
