# Generated by Django 4.2.20 on 2026-08-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0005_feeshare_fees_two_decimals'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementbatch',
            name='bank_txn_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='银行出款流水号'),
        ),
        migrations.AddField(
            model_name='settlementbatch',
            name='currency',
            field=models.CharField(blank=True, db_index=True, default='', max_length=3, verbose_name='币种'),
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['merchant', 'settle_date', 'currency'], name='settlement__merchan_b5114c_idx'),
        ),
    ]
