# Generated by Django 4.2.20 on 2026-07-10 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('date', models.DateField(verbose_name='日期')),
                ('from_currency', models.CharField(max_length=3, verbose_name='汇出币种')),
                ('to_currency', models.CharField(max_length=3, verbose_name='到账币种')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='汇率')),
                ('source', models.CharField(default='Bloomberg', max_length=64, verbose_name='来源')),
            ],
            options={
                'verbose_name': '汇率',
                'verbose_name_plural': '汇率',
                'db_table': 'exchange_rate',
                'ordering': ['-date', 'from_currency', 'to_currency'],
                'unique_together': {('date', 'from_currency', 'to_currency')},
            },
        ),
    ]
