# Generated by Django 4.2.20 on 2026-07-10 05:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_no', models.CharField(max_length=64, unique=True, verbose_name='申请单号')),
                ('diff_type', models.CharField(choices=[('amount', '金额差异'), ('count', '笔数差异'), ('status', '状态差异'), ('duplicate', '重复交易'), ('missing', '缺失交易')], default='amount', max_length=20, verbose_name='差异类型')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('order_no', models.CharField(blank=True, max_length=64, verbose_name='关联订单号')),
                ('bank_channel', models.CharField(blank=True, max_length=100, verbose_name='银行通道')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='差异金额')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('reason', models.TextField(verbose_name='差异原因')),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='调账金额')),
                ('applicant', models.CharField(max_length=50, verbose_name='申请人')),
                ('applicant_id', models.CharField(blank=True, max_length=64, verbose_name='申请人ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '调账申请',
                'verbose_name_plural': '调账申请',
                'db_table': 'adjustment_application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='AdjustmentApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approver', models.CharField(max_length=50, verbose_name='审批人')),
                ('approver_id', models.CharField(blank=True, max_length=64, verbose_name='审批人ID')),
                ('action', models.CharField(choices=[('approve', '通过'), ('reject', '拒绝'), ('return', '退回')], max_length=20, verbose_name='审批动作')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='审批时间')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='审批层级')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='adjustment.adjustmentapplication', verbose_name='调账申请')),
            ],
            options={
                'verbose_name': '调账审批',
                'verbose_name_plural': '调账审批',
                'db_table': 'adjustment_approval',
                'ordering': ['-approved_at'],
            },
        ),
    ]
