# Generated by Django 4.2.20 on 2026-07-06 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('order_no', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='平台订单号')),
                ('merchant_order_no', models.CharField(db_index=True, max_length=64, verbose_name='商户订单号')),
                ('unique_identification_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='汇款唯一识别号')),
                ('user_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户ID')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='币种')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='订单金额')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='手续费')),
                ('settle_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='结算金额')),
                ('pay_method', models.CharField(choices=[('ONLINE_BANK', '银行网银支付'), ('AUTHORIZED', '账户授权支付'), ('WIRE_TRANSFER', '转款汇款')], max_length=32, verbose_name='支付方式')),
                ('bank_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='银行编码')),
                ('bank_txn_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='银行交易流水号')),
                ('status', models.CharField(choices=[('PRE_CREATE', '预创建'), ('PENDING_PAY', '待收款'), ('PAY_RECEIVED', '已收款'), ('PENDING_SETTLE', '待清算'), ('SETTLED', '已清算'), ('CLOSED', '已关闭'), ('REFUNDING', '退款中'), ('REFUNDED', '已退款')], default='PRE_CREATE', max_length=20, verbose_name='状态')),
                ('status_history', models.JSONField(default=list, verbose_name='状态历史')),
                ('pay_received_at', models.DateTimeField(blank=True, null=True, verbose_name='收款时间')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='清算时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('expire_at', models.DateTimeField(verbose_name='过期时间')),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='幂等键')),
                ('signature', models.CharField(blank=True, max_length=512, verbose_name='请求签名')),
                ('notify_url', models.URLField(blank=True, max_length=512, null=True, verbose_name='通知地址')),
                ('notify_count', models.IntegerField(default=0, verbose_name='通知次数')),
                ('last_notify_at', models.DateTimeField(blank=True, null=True, verbose_name='最后通知时间')),
                ('notify_status', models.CharField(default='PENDING', max_length=16, verbose_name='通知状态')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='merchant.merchant', verbose_name='商户')),
            ],
            options={
                'verbose_name': '支付订单',
                'verbose_name_plural': '支付订单',
                'db_table': 'payment_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('refund_no', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='退款单号')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='退款金额')),
                ('refund_reason', models.CharField(max_length=256, verbose_name='退款原因')),
                ('status', models.CharField(choices=[('PENDING_REVIEW', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回'), ('PROCESSING', '处理中'), ('SUCCESS', '退款成功'), ('FAILED', '退款失败')], default='PENDING_REVIEW', max_length=20, verbose_name='状态')),
                ('reviewed_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='审核人')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('bank_refund_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='银行退款流水')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款完成时间')),
                ('fail_reason', models.CharField(blank=True, max_length=256, verbose_name='失败原因')),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payment.paymentorder', verbose_name='原支付订单')),
            ],
            options={
                'verbose_name': '退款单',
                'verbose_name_plural': '退款单',
                'db_table': 'refund_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['merchant_order_no', 'merchant'], name='payment_ord_merchan_959462_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user_id', 'status'], name='payment_ord_user_id_724e74_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'created_at'], name='payment_ord_status_8c5a85_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['merchant', 'pay_received_at'], name='payment_ord_merchan_05b328_idx'),
        ),
    ]
