# Generated by Django 4.2.20 on 2026-07-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='beneficiary_account',
            field=models.CharField(default='', max_length=64, verbose_name='收款账号'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='beneficiary_address',
            field=models.CharField(default='', max_length=256, verbose_name='收款人地址'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='beneficiary_bank',
            field=models.CharField(default='', max_length=128, verbose_name='收款银行'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='beneficiary_name',
            field=models.CharField(default='', max_length=128, verbose_name='收款人名称'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='beneficiary_swift',
            field=models.CharField(default='', max_length=16, verbose_name='SWIFT代码'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='contract_file',
            field=models.CharField(blank=True, max_length=512, verbose_name='合同文件路径'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='fee_bearing',
            field=models.CharField(choices=[('OUR', '汇款人承担'), ('SHA', '双方共担'), ('BEN', '收款人承担')], default='OUR', max_length=10, verbose_name='费用承担方式'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='from_currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='汇出币种'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='remittance_purpose',
            field=models.CharField(default='', max_length=256, verbose_name='汇款用途'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='review_comment',
            field=models.CharField(blank=True, max_length=512, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='to_currency',
            field=models.CharField(default='CNY', max_length=3, verbose_name='到账币种'),
        ),
    ]
