# Generated by Django 4.2.20 on 2026-07-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentorder_beneficiary_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='prn_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True, verbose_name='PRN码'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('PRE_CREATE', '预创建'), ('PENDING_REVIEW', '待审核'), ('PENDING_PAY', '待收款'), ('PAY_RECEIVED', '已收款'), ('PENDING_SETTLE', '待清算'), ('SETTLED', '已清算'), ('CLOSED', '已关闭'), ('REFUNDING', '退款中'), ('REFUNDED', '已退款')], default='PRE_CREATE', max_length=20, verbose_name='状态'),
        ),
    ]
