# Generated by Django 4.2.30 on 2026-07-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentorder_prn_code_alter_paymentorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('PRE_CREATE', '预创建'), ('PENDING_REVIEW', '待审核'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('PENDING_PAY', '待收款'), ('PAY_RECEIVED', '已收款'), ('PENDING_SETTLE', '待清算'), ('SETTLED', '已清算'), ('CLOSED', '已关闭'), ('REFUNDING', '退款中'), ('REFUNDED', '已退款')], default='PRE_CREATE', max_length=20, verbose_name='状态'),
        ),
    ]
