# Generated by Django 4.2.20 on 2026-07-21 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_add_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundFeeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('fee_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='例如 1.50 表示 1.50%，退款金额 × 费率 = 手续费', max_digits=5, verbose_name='退款手续费率(%)')),
                ('updated_by', models.CharField(blank=True, max_length=64, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '退款手续费配置',
                'verbose_name_plural': '退款手续费配置',
                'db_table': 'refund_fee_config',
            },
        ),
        migrations.AddField(
            model_name='refundorder',
            name='refund_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='退款手续费金额'),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='refund_fee_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='退款手续费率(%)'),
        ),
    ]
