# Generated by Django 4.2.20 on 2026-08-20 03:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_refundfeeconfig_refundorder_refund_fee_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRNConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('prefix', models.CharField(default='', max_length=8, verbose_name='前缀')),
                ('length', models.IntegerField(default=6, verbose_name='主体长度(不含前缀与校验位)')),
                ('use_check_digit', models.BooleanField(default=False, verbose_name='是否启用校验位')),
                ('charset', models.CharField(choices=[('NUMERIC', '纯数字'), ('ALNUM', '数字+大写字母')], default='NUMERIC', max_length=8, verbose_name='字符集')),
                ('updated_by', models.CharField(blank=True, max_length=64, verbose_name='修改人')),
            ],
            options={
                'verbose_name': 'PRN配置',
                'verbose_name_plural': 'PRN配置',
                'db_table': 'prn_config',
            },
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='prn_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='PRN码'),
        ),
    ]
