# Generated by Django 4.2.20 on 2026-08-27 02:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_p0_core_gaps'),
        ('merchant', '0006_feature_gap_split_and_recon_type'),
        ('payment', '0006_prnconfig_alter_paymentorder_prn_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrnIssuance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('prn_code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='PRN码')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='金额')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='币种')),
                ('reference', models.CharField(blank=True, max_length=128, verbose_name='业务参考号')),
                ('status', models.CharField(choices=[('ISSUED', '已签发'), ('BOUND', '已绑定订单'), ('MATCHED', '已匹配收款'), ('EXPIRED', '已过期')], default='ISSUED', max_length=16, verbose_name='状态')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prn_issuances', to='agent.agent', verbose_name='代理商')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prn_issuances', to='merchant.merchant', verbose_name='关联商户')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prn_issuances', to='payment.paymentorder', verbose_name='绑定订单')),
            ],
            options={
                'verbose_name': 'PRN签发',
                'verbose_name_plural': 'PRN签发',
                'db_table': 'prn_issuance',
                'ordering': ['-created_at'],
            },
        ),
    ]
