# Generated by Django 4.2.20 on 2026-08-30 06:59

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
import uuid


def populate_legacy_snapshots(apps, schema_editor):
    PaymentOrder = apps.get_model("payment", "PaymentOrder")
    DailyUsage = apps.get_model("payment", "MerchantDailyRemittanceUsage")
    usage_totals = {}
    for order in PaymentOrder.objects.all().iterator():
        order.sender_total_amount = order.amount
        order.fee_currency = order.from_currency or order.currency or ""
        if order.from_currency and order.from_currency == order.to_currency:
            order.exchange_rate = Decimal("1")
            order.rate_source = "LEGACY_SAME_CURRENCY"
        order.save(update_fields=[
            "sender_total_amount", "fee_currency", "exchange_rate", "rate_source",
        ])

        if not order.is_deleted and order.status not in ("CLOSED", "REFUNDED"):
            usage_date = timezone.localtime(order.created_at).date()
            key = (order.merchant_id, usage_date)
            current_amount, current_count = usage_totals.get(
                key, (Decimal("0"), 0)
            )
            usage_totals[key] = (
                current_amount + order.amount,
                current_count + 1,
            )

    for (merchant_id, usage_date), values in usage_totals.items():
        DailyUsage.objects.create(
            merchant_id=merchant_id,
            usage_date=usage_date,
            total_amount=values[0],
            order_count=values[1],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_lifecycle_controls'),
        ('payment', '0007_p0_core_gaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='applied_fee_model',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='费率模式快照'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='applied_fee_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='费率快照'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='applied_fixed_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='固定费快照'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='使用汇率'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='fee_currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='手续费币种'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='rate_source',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='汇率来源'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='request_payload_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='提交参数摘要'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='sender_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='汇款方应付总额'),
        ),
        migrations.CreateModel(
            name='RemittanceQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('quote_no', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='报价编号')),
                ('user_id', models.CharField(blank=True, default='', max_length=64, verbose_name='客户用户ID')),
                ('actor_type', models.CharField(choices=[('ADMIN', '运营'), ('CUSTOMER', '客户')], max_length=16, verbose_name='报价发起方')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='汇款本金')),
                ('from_currency', models.CharField(max_length=3, verbose_name='汇出币种')),
                ('to_currency', models.CharField(max_length=3, verbose_name='到账币种')),
                ('fee_bearing', models.CharField(choices=[('OUR', '汇款人承担'), ('SHA', '双方共担'), ('BEN', '收款人承担')], max_length=10, verbose_name='费用承担方式')),
                ('fee_currency', models.CharField(max_length=3, verbose_name='手续费币种')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='手续费')),
                ('sender_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='汇款方承担手续费')),
                ('beneficiary_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='收款方承担手续费')),
                ('sender_total_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='汇款方应付总额')),
                ('settle_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='预计到账金额')),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='使用汇率')),
                ('rate_source', models.CharField(max_length=64, verbose_name='汇率来源')),
                ('fee_model', models.CharField(max_length=16, verbose_name='费率模式')),
                ('fee_rate', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='费率快照')),
                ('fixed_fee', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='固定费快照')),
                ('payload_hash', models.CharField(max_length=64, verbose_name='报价参数摘要')),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('USED', '已使用'), ('EXPIRED', '已过期')], default='ACTIVE', max_length=16, verbose_name='报价状态')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='报价过期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittance_quotes', to='merchant.merchant', verbose_name='商户')),
            ],
            options={
                'db_table': 'remittance_quote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantDailyRemittanceUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('usage_date', models.DateField(verbose_name='业务日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='已预留汇款金额')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='已预留订单数')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_remittance_usage', to='merchant.merchant', verbose_name='商户')),
            ],
            options={
                'db_table': 'merchant_daily_remittance_usage',
            },
        ),
        migrations.RunPython(
            populate_legacy_snapshots,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_order', to='payment.remittancequote', verbose_name='汇款报价'),
        ),
        migrations.AddConstraint(
            model_name='remittancequote',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['ACTIVE', 'USED', 'EXPIRED'])), name='remittance_quote_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='merchantdailyremittanceusage',
            constraint=models.UniqueConstraint(fields=('merchant', 'usage_date'), name='unique_merchant_daily_remittance_usage'),
        ),
    ]
