# Generated by Django 4.2.20 on 2026-09-13 05:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_lifecycle_controls'),
        ('payment', '0012_agent_payout_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCreditNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('notification_no', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='通知单号')),
                ('txn_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='银行流水号')),
                ('txn_time', models.DateTimeField(db_index=True, verbose_name='入账时间')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='入账金额')),
                ('currency', models.CharField(max_length=3, verbose_name='币种')),
                ('remark', models.CharField(blank=True, default='', max_length=256, verbose_name='银行附言')),
                ('prn_code', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='PRN码')),
                ('bank_code', models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='入金银行编码')),
                ('bank_name', models.CharField(blank=True, default='', max_length=128, verbose_name='入金银行')),
                ('account_no', models.CharField(blank=True, default='', max_length=64, verbose_name='入金账号')),
                ('order_no', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='订单号')),
                ('merchant_no', models.CharField(blank=True, default='', max_length=32, verbose_name='客户编号')),
                ('merchant_name', models.CharField(blank=True, default='', max_length=128, verbose_name='客户名称')),
                ('status', models.CharField(choices=[('RECEIVED', '已接收'), ('MATCHED', '已匹配'), ('MISMATCH', '金额不符'), ('UNMATCHED', '未匹配')], db_index=True, default='RECEIVED', max_length=16, verbose_name='匹配状态')),
                ('source', models.CharField(choices=[('MOCK', '模拟入金'), ('BANK_API', '银行接口')], default='MOCK', max_length=16, verbose_name='来源')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='原始报文')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_credit_notifications', to='merchant.merchant', verbose_name='匹配客户')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_credit_notifications', to='payment.paymentorder', verbose_name='匹配订单')),
            ],
            options={
                'verbose_name': '银行入金通知',
                'verbose_name_plural': '银行入金通知',
                'db_table': 'bank_credit_notification',
                'ordering': ['-txn_time', '-created_at'],
            },
        ),
    ]
